# Generated by Django 5.1.7 on 2025-04-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0002_rename_id_questao_escolha_questao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name='Data Publicação:'),
        ),
    ]
