# Generated by Django 5.1.7 on 2025-04-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0004_alter_questao_texto_questao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='texto_questao',
            field=models.CharField(max_length=200, verbose_name='Texto da Questão'),
        ),
    ]
