# Generated by Django 5.1.7 on 2025-04-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0005_alter_questao_texto_questao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolha',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisas.questao', verbose_name='Questão: '),
        ),
    ]
