# Generated by Django 5.1.7 on 2025-04-02 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0006_alter_escolha_questao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolha',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisas.questao'),
        ),
    ]
